category_layout: news.html
category_path: /news/
excerpt_separator: <!--more-->
paginate: 9999 # we dont use this but the category pages ext does
permalink: /news/:year/:title:output_ext

exclude:
  - README.md

navigation:
    - Home: /
      About: /about.html
      News: /news/
      Downloads: https://github.com/anope/anope/releases
      Team: /team.html
      Contact: /contact.html

    - Forum: https://github.com/orgs/anope/discussions
      Modules: https://modules.anope.org
      Wiki: https://wiki.anope.org
      FAQ: https://wiki.anope.org/index.php/2.0/FAQ
      Bug Tracker: https://github.com/anope/anope/issues
      Paste Bin: https://pastebin.anope.org

    - Docker Hub: https://hub.docker.com/r/anope/anope
      GitHub: https://github.com/anope/anope

    - Bluesky: https://bsky.app/profile/anope.bsky.social
      Mastodon: https://fosstodon.org/@anope
      RSS: /feed.xml

plugins:
- jekyll-category-pages
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-sitemap

releases:
  devel:
    version: 2.1.20
    date: 2025-12-01
    news: /news/2025/anope-2120-release.html
    source: https://github.com/anope/anope/archive/refs/tags/2.1.20.tar.gz
    windows: https://github.com/anope/anope/releases/download/2.1.20/anope-2.1.20.exe
  stable:
    version: 2.0.18
    date: 2025-05-08
    news: /news/2025/anope-2018-release.html
    source: https://github.com/anope/anope/archive/refs/tags/2.0.18.tar.gz
    windows: https://github.com/anope/anope/releases/download/2.0.18/anope-2.0.18.exe
